### ISSUE TITLE
defect: Amplify build script - detect back-end environment automatically

### ISSUE THREAD

**Issue by soumik-mukherjee** [soumik-mukherjee/amplify-gatsby-webapp-template#20]
**Describe the bug**
Remove the reference to a specific environment `dev` in the following code:

```yaml
applications:
  - backend:
      phases:
        build:
          commands:
            - '# Execute Amplify CLI with the helper script'
            - amplifyPush --environment dev --simple
```

**To Reproduce**
1. Create a change in the downstream `demo-credit-card-app`. Merge the change to `develop` branch
2. Observe build output - script should select backend env based on frontend auto-build settings

**Expected behavior**
In the `demo-credit-card-app`, the build should automatically select the `develop` env

**Screenshots**
n/a

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a
